[Service]
WorkingDirectory=/home/bueno/HBlink4-experimental-v2
Environment=BUENODMR_PUBLIC_WEB=1
ExecStart=
ExecStart=/home/bueno/HBlink4/venv/bin/python /home/bueno/HBlink4-experimental-v2/dashboard/server.py
