[Service]
WorkingDirectory=/home/bueno/HBlink4-experimental-v2
ExecStart=
ExecStart=/home/bueno/HBlink4/venv/bin/python /home/bueno/HBlink4-experimental-v2/hblink4/hblink.py /home/bueno/HBlink4-experimental-v2/config/config.json
